#![no_std]
#![no_main]
#![feature(type_alias_impl_trait)]
#![feature(async_closure)]
#![feature(
    maybe_uninit_uninit_array,
    const_maybe_uninit_uninit_array,
    maybe_uninit_slice,
    maybe_uninit_write_slice
)]
#![feature(const_mut_refs)]
#![feature(adt_const_params)]
#![feature(ptr_metadata)]
#![feature(async_fn_in_trait)]
#![feature(const_fn_floating_point_arithmetic)]